# Generated by Django 2.1.7 on 2020-01-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbdailyrecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=8)),
                ('attender', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('partner', models.CharField(max_length=256)),
                ('tag', models.CharField(max_length=6)),
                ('customer', models.IntegerField(default=0)),
                ('productdesign', models.IntegerField(default=0)),
                ('teamwork', models.IntegerField(default=0)),
                ('orgnization', models.IntegerField(default=0)),
                ('management', models.IntegerField(default=0)),
                ('operation', models.IntegerField(default=0)),
                ('competence', models.IntegerField(default=0)),
                ('extra', models.CharField(max_length=512)),
                ('updatetime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbproject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=128)),
                ('projectname', models.CharField(max_length=256)),
                ('attender', models.CharField(max_length=256)),
                ('customer', models.IntegerField(default=0)),
                ('productdesign', models.IntegerField(default=0)),
                ('teamwork', models.IntegerField(default=0)),
                ('orgnization', models.IntegerField(default=0)),
                ('management', models.IntegerField(default=0)),
                ('operation', models.IntegerField(default=0)),
                ('competence', models.IntegerField(default=0)),
                ('updatetime', models.DateField(auto_now=True)),
            ],
        ),
    ]
