# Generated by Django 2.1.7 on 2020-02-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyReport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbdailyrecord',
            name='project',
            field=models.CharField(default='', max_length=6),
        ),
    ]
