# Generated by Django 2.1.7 on 2020-03-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyReport', '0002_tbdailyrecord_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbdailyrecord',
            name='date',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='tbdailyrecord',
            name='tag',
            field=models.CharField(max_length=12),
        ),
    ]
