# Generated by Django 2.1.7 on 2020-03-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyReport', '0003_auto_20200303_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbdailyrecord',
            name='attender',
        ),
        migrations.RemoveField(
            model_name='tbdailyrecord',
            name='competence',
        ),
        migrations.RemoveField(
            model_name='tbdailyrecord',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='tbdailyrecord',
            name='management',
        ),
        migrations.RemoveField(
            model_name='tbdailyrecord',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='tbdailyrecord',
            name='orgnization',
        ),
        migrations.RemoveField(
            model_name='tbdailyrecord',
            name='productdesign',
        ),
        migrations.RemoveField(
            model_name='tbdailyrecord',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tbdailyrecord',
            name='teamwork',
        ),
        migrations.AlterField(
            model_name='tbdailyrecord',
            name='project',
            field=models.CharField(default='', max_length=512),
        ),
    ]
